@host = http://localhost:3000

## AUTORES ##

# Obtener todos
###
GET {{host}}/api/autores

# Crear autor
###
POST {{host}}/api/autores/registro
Content-Type: application/json

{
    "nombre": "César Ibáñez",
    "email": "cesaribanez@email.com",
    "imagen": "foto_cesar.jpg"
}


## POSTS ##

# Obtener todos
###
GET {{host}}/api/posts

#Create post
###
POST {{host}}/api/posts/publish
Content-Type: application/json

{
    "titulo": "Título del post",
    "descripcion": "Descripción del post creado",
    "fechacrea": "",
    "categoria": "Categoria",
    "autores_id": "1"
}