@host = http://localhost:3000

## AUTORES ##

# Obtener todos
###
GET {{host}}/api/autores

# Crear autor
###
POST {{host}}/api/autores/registro
Content-Type: application/json

{
    "nombre": "Usuario Uno",
    "email": "usuariouno@email.com",
    "imagen": "foto_usuariouno.jpg"
}

## POSTS ##

# Obtener todos los posts
###
GET {{host}}/api/posts

# Obtener todos los posts de un usuario
###
GET {{host}}/api/posts/3

# Crear post
###
POST {{host}}/api/posts/publish
Content-Type: application/json

{
    "titulo": "Título del post",
    "descripcion": "Descripción del post creado",
    "categoria": "Categoria",
    "autores_id": "4"
}