-- MySQL Script generated by MySQL Workbench
-- Sun Jun  8 11:48:59 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema actividad8
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `actividad8` ;

-- -----------------------------------------------------
-- Schema actividad8
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `actividad8` DEFAULT CHARACTER SET utf8 ;
USE `actividad8` ;

-- -----------------------------------------------------
-- Table `actividad8`.`autores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `actividad8`.`autores` ;

CREATE TABLE IF NOT EXISTS `actividad8`.`autores` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(200) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `imagen` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `actividad8`.`posts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `actividad8`.`posts` ;

CREATE TABLE IF NOT EXISTS `actividad8`.`posts` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(200) NOT NULL,
  `descripcion` TEXT NOT NULL,
  `fechacrea` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `categoria` VARCHAR(45) NULL,
  `autores_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_posts_autores_idx` (`autores_id` ASC) VISIBLE,
  CONSTRAINT `fk_posts_autores`
    FOREIGN KEY (`autores_id`)
    REFERENCES `actividad8`.`autores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
